### ISSUE TITLE
Add SnakBar on double press exit

### ISSUE THREAD

**Issue by Prashant4900** [Prashant4900/flutter_const#3]

**Comment by Abhinav-CHD** [comment]
@Prashant4900 I would like to work on this issue

**Comment by Prashant4900** [comment]
> @Prashant4900 I would like to work on this issue

that great

**Comment by Abhinav-CHD** [comment]
Hey can you specify the location where the onpressed for back button is specified (ie navigation.pop)? I'm having a hard time finding it.

**Comment by Prashant4900** [comment]
> Hey can you specify the location where the onpressed for back button is specified (ie navigation.pop)? I'm having a hard time finding it.

you might know how WillPopScope Widget will work its a parent widget on Scaffoled and its hold onWillPop Arguments so on that place just pass our fcOnWillPop()

child: WillPopScope(

        onWillPop: fcOnWillPop,

        child: ListView(),

      ),
      
For more detail see the readme file. So when you did that then the function is activated.
Suppose if you do that on the home screen and press the back button on single time then the snack bar needs to show
